"""
Django settings for restaurant_management project.

Generated by 'django-admin startproject' using Django 4.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-s^x_u!itekxd=@a3o3zv4d%hw$j6d#2v358wgltxl8rc(-^t&p'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'home',
    'account',
    'products',
    'orders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'restaurant_management.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'restaurant_management.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Restaurant Management System</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box  }

        body {
            font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            line-height: 1.6;
            color: #2d3748;
            background: linear-gradient(135deg, #1a202c 0%, #2d3748 50%, #4a5568 100%);
            min-height: 100vh;
            overflow-x: hidden;
        }

        /* Animated background elements */
        .bg-animation {
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            z-index: -1;
            opacity: 0.05;
        }

        .bg-element {
            position: absolute;
            border: 1px solid #fff;
            border-radius: 10px;
            animation: float 8s ease-in-out infinite;
        }

        .bg-element:nth-child(1) { width: 40px; height: 40px; top: 10%; left: 10%; animation-delay: 0s; }
        .bg-element:nth-child(2) { width: 60px; height: 60px; top: 30%; left: 80%; animation-delay: 2s; }
        .bg-element:nth-child(3) { width: 30px; height: 30px; top: 70%; left: 20%; animation-delay: 4s; }
        .bg-element:nth-child(4) { width: 50px; height: 50px; top: 60%; left: 70%; animation-delay: 6s; }

        @keyframes float {
            0%, 100% { transform: translateY(0px) rotate(0deg); }
            50% { transform: translateY(-30px) rotate(180deg); }
        }

        /* Header */
        header {
            background: rgba(26, 32, 44, 0.9);
            backdrop-filter: blur(10px);
            border-bottom: 1px solid rgba(255, 255, 255, 0.1);
            padding: 1rem 0;
            position: sticky;
            top: 0;
            z-index: 100;
        }

        nav {
            max-width: 1200px;
            margin: 0 auto;
            padding: 0 2rem;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }

        .logo {
            font-size: 1.8rem;
            font-weight: 800;
            color: white;
            text-decoration: none;
            background: linear-gradient(45deg, #f56565, #ed8936);
            background-clip: text;
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
        }

        .nav-links {
            display: flex;
            list-style: none;
            gap: 2rem;
        }

        .nav-links a {
            color: #e2e8f0;
            text-decoration: none;
            font-weight: 500;
            padding: 0.5rem 1rem;
            border-radius: 8px;
            transition: all 0.3s ease;
            position: relative;
        }

        .nav-links a:hover {
            background: rgba(245, 101, 101, 0.1);
            color: #f56565;
            transform: translateY(-2px);
        }

        /* Hero Section */
        .hero {
            max-width: 1200px;
            margin: 0 auto;
            padding: 4rem 2rem;
            text-align: center;
            color: white;
        }

        .hero h1 {
            font-size: clamp(2.5rem, 6vw, 4rem);
            font-weight: 900;
            margin-bottom: 1.5rem;
            background: linear-gradient(45deg, #ffffff, #f7fafc);
            background-clip: text;
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            animation: slideInUp 1s ease-out;
        }

        .hero p {
            font-size: 1.25rem;
            margin-bottom: 2rem;
            opacity: 0.9;
            max-width: 700px;
            margin-left: auto;
            margin-right: auto;
            animation: slideInUp 1s ease-out 0.2s both;
        }

        .hero-buttons {
            display: flex;
            gap: 1rem;
            justify-content: center;
            flex-wrap: wrap;
            animation: slideInUp 1s ease-out 0.4s both;
        }

        .cta-button {
            background: linear-gradient(45deg, #f56565, #ed8936);
            color: white;
            padding: 1rem 2rem;
            font-size: 1.1rem;
            font-weight: 600;
            border: none;
            border-radius: 10px;
            cursor: pointer;
            text-decoration: none;
            display: inline-block;
            transition: all 0.3s ease;
            box-shadow: 0 8px 25px rgba(245, 101, 101, 0.3);
        }

        .cta-button:hover {
            transform: translateY(-3px);
            box-shadow: 0 12px 35px rgba(245, 101, 101, 0.4);
        }

        .cta-button.secondary {
            background: transparent;
            border: 2px solid #f56565;
            box-shadow: none;
        }

        .cta-button.secondary:hover {
            background: #f56565;
            box-shadow: 0 8px 25px rgba(245, 101, 101, 0.3);
        }

        /* Features Section */
        .features {
            background: rgba(255, 255, 255, 0.95);
            margin: 4rem 2rem;
            padding: 4rem 2rem;
            border-radius: 20px;
            max-width: 1200px;
            margin-left: auto;
            margin-right: auto;
            box-shadow: 0 20px 60px rgba(0, 0, 0, 0.15);
        }

        .features h2 {
            text-align: center;
            font-size: 2.5rem;
            font-weight: 800;
            margin-bottom: 3rem;
            background: linear-gradient(45deg, #1a202c, #2d3748);
            background-clip: text;
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
        }

        .feature-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
            gap: 2rem;
        }

        .feature-card {
            background: white;
            padding: 2.5rem;
            border-radius: 16px;
            text-align: center;
            transition: all 0.3s ease;
            border: 1px solid rgba(0, 0, 0, 0.05);
            position: relative;
            overflow: hidden;
        }

        .feature-card::before {
            content: '';
            position: absolute;
            top: 0;
            left: -100%;
            width: 100%;
            height: 3px;
            background: linear-gradient(90deg, #f56565, #ed8936);
            transition: left 0.5s ease;
        }

        .feature-card:hover::before {
            left: 0;
        }

        .feature-card:hover {
            transform: translateY(-10px);
            box-shadow: 0 25px 50px rgba(0, 0, 0, 0.1);
        }

        .feature-icon {
            width: 70px;
            height: 70px;
            background: linear-gradient(45deg, #f56565, #ed8936);
            border-radius: 50%;
            display: flex;
            align-items: center;
            justify-content: center;
            margin: 0 auto 1.5rem;
            font-size: 2rem;
            color: white;
        }

        .feature-card h3 {
            font-size: 1.5rem;
            font-weight: 700;
            margin-bottom: 1rem;
            color: #1a202c;
        }

        .feature-card p {
            color: #4a5568;
            line-height: 1.7;
        }

        /* Stats Section */
        .stats {
            background: rgba(245, 101, 101, 0.1);
            margin: 4rem 2rem;
            padding: 3rem 2rem;
            border-radius: 20px;
            max-width: 1200px;
            margin-left: auto;
            margin-right: auto;
            backdrop-filter: blur(10px);
        }

        .stats h2 {
            text-align: center;
            font-size: 2rem;
            font-weight: 800;
            margin-bottom: 2rem;
            color: white;
        }

        .stats-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 2rem;
            text-align: center;
        }

        .stat-item {
            color: white;
        }

        .stat-number {
            font-size: 3rem;
            font-weight: 900;
            display: block;
            background: linear-gradient(45deg, #ffffff, #f7fafc);
            background-clip: text;
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
        }

        .stat-label {
            font-size: 1.1rem;
            opacity: 0.9;
            margin-top: 0.5rem;
        }

        /* Footer */
        footer {
            background: rgba(0, 0, 0, 0.2);
            color: white;
            text-align: center;
            padding: 3rem 2rem;
            margin-top: 4rem;
            backdrop-filter: blur(10px);
        }

        .footer-content {
            max-width: 1200px;
            margin: 0 auto;
        }

        .footer-links {
            display: flex;
            justify-content: center;
            gap: 2rem;
            margin-bottom: 2rem;
            flex-wrap: wrap;
        }

        .footer-links a {
            color: #e2e8f0;
            text-decoration: none;
            transition: color 0.3s ease;
        }

        .footer-links a:hover {
            color: #f56565;
        }

        /* Animations */
        @keyframes slideInUp {
            from {
                opacity: 0;
                transform: translateY(30px);
            }
            to {
                opacity: 1;
                transform: translateY(0);
            }
        }

        /* Responsive Design */
        @media (max-width: 768px) {
            .nav-links {
                display: none;
            }
            
            .hero {
                padding: 2rem 1rem;
            }
            
            .hero-buttons {
                flex-direction: column;
                align-items: center;
            }
            
            .features, .stats {
                margin: 2rem 1rem;
                padding: 2rem 1rem;
            }
            
            .feature-grid, .stats-grid {
                grid-template-columns: 1fr;
                gap: 1.5rem;
            }
            
            .footer-links {
                flex-direction: column;
                gap: 1rem;
            }
        }
    </style>
</head>
<body>
    <div class="bg-animation">
        <div class="bg-element"></div>
        <div class="bg-element"></div>
        <div class="bg-element"></div>
        <div class="bg-element"></div>
    </div>

    <header>
        <nav>
            <a href="#" class="logo">RestaurantPro</a>
            <ul class="nav-links">
                <li><a href="#home">Home</a></li>
                <li><a href="#products">Products</a></li>
                <li><a href="#orders">Orders</a></li>
                <li><a href="#account">Account</a></li>
            </ul>
        </nav>
    </header>

    <main>
        <section class="hero">
            <h1>Restaurant Management System</h1>
            <p>Streamline your restaurant operations with our comprehensive management solution. Handle orders, manage inventory, track sales, and optimize your restaurant's performance all in one place.</p>
            <div class="hero-buttons">
                <a href="#" class="cta-button">Get Started</a>
                <a href="#" class="cta-button secondary">View Demo</a>
            </div>
        </section>

        <section class="features">
            <h2>Powerful Features for Your Restaurant</h2>
            <div class="feature-grid">
                <div class="feature-card">
                    <div class="feature-icon">📋</div>
                    <h3>Order Management</h3>
                    <p>Efficiently track and manage all incoming orders with real-time updates, order status tracking, and seamless kitchen integration.</p>
                </div>
                <div class="feature-card">
                    <div class="feature-icon">🏠</div>
                    <h3>Dashboard Analytics</h3>
                    <p>Get comprehensive insights into your restaurant's performance with detailed analytics, sales reports, and trend analysis.</p>
                </div>
                <div class="feature-card">
                    <div class="feature-icon">🍽️</div>
                    <h3>Product Catalog</h3>
                    <p>Manage your menu items, pricing, ingredients, and availability with an intuitive product management system.</p>
                </div>
                <div class="feature-card">
                    <div class="feature-icon">👥</div>
                    <h3>Account Management</h3>
                    <p>Handle customer accounts, loyalty programs, and staff management with secure user authentication and role-based access.</p>
                </div>
                <div class="feature-card">
                    <div class="feature-icon">📊</div>
                    <h3>Sales Tracking</h3>
                    <p>Monitor daily, weekly, and monthly sales performance with detailed reporting and revenue optimization tools.</p>
                </div>
                <div class="feature-card">
                    <div class="feature-icon">⚙️</div>
                    <h3>System Integration</h3>
                    <p>Seamlessly integrate with POS systems, payment gateways, and third-party delivery platforms for complete automation.</p>
                </div>
            </div>
        </section>

        <section class="stats">
            <h2>Trusted by Restaurant Owners</h2>
            <div class="stats-grid">
                <div class="stat-item">
                    <span class="stat-number">500+</span>
                    <div class="stat-label">Restaurants Served</div>
                </div>
                <div class="stat-item">
                    <span class="stat-number">50K+</span>
                    <div class="stat-label">Orders Processed</div>
                </div>
                <div class="stat-item">
                    <span class="stat-number">99.9%</span>
                    <div class="stat-label">Uptime</div>
                </div>
                <div class="stat-item">
                    <span class="stat-number">24/7</span>
                    <div class="stat-label">Support</div>
                </div>
            </div>
        </section>
    </main>

    <footer>
        <div class="footer-content">
            <div class="footer-links">
                <a href="#about">About Us</a>
                <a href="#contact">Contact</a>
                <a href="#privacy">Privacy Policy</a>
                <a href="#terms">Terms of Service</a>
                <a href="#support">Support</a>
            </div>
            <p>&copy; 2025 RestaurantPro Management System. All rights reserved.</p>
        </div>
    </footer>
</body>
</html>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>404 - Page Not Found</title>
</head>
<body>
    <div style="text-align: center; padding: 50px; font-family: Arial, sans-serif;">
        <h1 style="font-size: 72px; color: #e74c3c; margin: 0;">404</h1>
        <h2 style="color: #2c3e50; margin: 20px 0;">Oops! Page Not Found</h2>
        <p style="font-size: 18px; color: #7f8c8d; margin: 20px 0;">
            The page you're looking for doesn't exist or has been moved.
        </p>
        
        <div style="margin: 40px 0;">
            <a href="/" style="
                background-color: #3498db; 
                color: white; 
                padding: 12px 24px; 
                text-decoration: none; 
                border-radius: 5px; 
                font-weight: bold;
                margin-right: 10px;
            ">Go Home</a>
            
            <a href="javascript:history.back()" style="
                background-color: #95a5a6; 
                color: white; 
                padding: 12px 24px; 
                text-decoration: none; 
                border-radius: 5px; 
                font-weight: bold;
            ">Go Back</a>
        </div>
        
        <div style="margin-top: 30px;">
            <h3 style="color: #2c3e50;">What can you do?</h3>
            <ul style="list-style: none; padding: 0; color: #7f8c8d;">
                <li>• Check the URL for typing errors</li>
                <li>• Return to the homepage</li>
                <li>• Use the navigation menu</li>
                <li>• Contact support if you need help</li>
            </ul>
        </div>
        
        <hr style="margin: 40px 0; border: 1px solid #ecf0f1;">
        
        <p style="color: #bdc3c7; font-size: 14px;">
            Error Code: 404 | RestaurantPro Management System
        </p>
    </div>
</body>
</html>